# Generated by Django 6.0.2 on 2026-04-06 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('id_number', models.CharField(max_length=20, unique=True, verbose_name='ID Number')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('county', models.CharField(max_length=100, verbose_name='County')),
                ('sub_county', models.CharField(max_length=100, verbose_name='Sub-County')),
                ('ward', models.CharField(max_length=100, verbose_name='Ward')),
                ('farm_name', models.CharField(max_length=200, verbose_name='Farm Name')),
                ('animal_type', models.CharField(choices=[('GOAT', 'Goat'), ('SHEEP', 'Sheep')], max_length=5, verbose_name='Type of Animal')),
                ('number_of_animals', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of Animals')),
                ('animal_age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Age of Animals (months)')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Farmer',
                'verbose_name_plural': 'Farmers',
                'ordering': ['-registration_date'],
            },
        ),
    ]
